Enhancement:
  title: "^feat:.*"

BugFix:
  title: "^fix:.*"

Documentation:
  title: "^docs:.*"

Build:
  title: "^build:.*"

CI:
  title: "^ci:.*"

Test:
  title: "^test:.*"

Chore:
  title: "^chore:.*"

WIP:
  title: "^WIP:.*"
  mergeable: false
