name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  ## 🚀  Contributors
  Thanks to the following contributors in this release: 
  $CONTRIBUTORS
  
categories:
  - title: '✨ Enhancements'
    semver-increment: 'minor'
    when:
      label: 'Enhancement'
  - title: '🐛 Bug Fixes'
    semver-increment: 'patch'
    when:
      labels:
        - 'BugFix'
  - title: '🔄 Refactor'
    when:
      label: 'Refactor'
  - title: '📦 Dependencies'
    semver-increment: 'patch'
    when:
      labels:
        - 'Dependencies'
  - title: '🛠️ Pipeline'
    when:
      labels:
        - 'CI'
        - 'Build'
  - title: '🧰 Maintenance'
    when:
      label: 'Chore'
  - title: '🧪 Tests'
    when:
      labels:
        - 'Test'
  - title: '📚 Documentation'
    when:
      labels:
        - 'Documentation'
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      labels:
        - 'BreakingChange'
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      labels:
        - 'Hotfixes'

version-resolver:
  default: patch
  
prerelease: false
contribution-template: '- $NAME contributed via $PULL_REQUEST'
