name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

categories:
  - title: 'Enhancements'
    label: 'Enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'BugFix'
  - title: 'Refactor'
    label: 'Refactor'
  - title: 'Dependencies'
    labels:
      - 'Dependencies'
  - title: 'Pipeline'
    labels:
      - 'CI'
      - 'Build'
  - title: '🧰 Maintenance'
    label: 'Chore'  
  - title: '📚 Documentation'
    labels:
      - 'Docs'

version-resolver:
  major:
    labels:
      - 'BreakingChange'
  minor:
    labels:
      - 'Enhancement'
  patch:
    labels:
      - 'BugFix'
      - 'Dependencies'
  default: patch
  
prerelease: false
prerelease-identifier: 'rc'
